services:
  cs2updatebot:
    image: seristo/cs2-update-docker:arm64
    container_name: cs2updatebot
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./appdata:/app/data
    restart: unless-stopped
