{
 "title": "cs2updatebot",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CORE METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last run",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(bot_processing_duration_seconds_count)*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSS response success rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(bot_rss_responses_total{result=\"success\"} / ignoring(result) bot_rss_checks_total)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last update timestamp",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bot_last_update_timestamp_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(bot_processing_duration_seconds_sum[10m]) / rate(bot_processing_duration_seconds_count[10m])",
     "legendFormat": "processing_time"
    }
   ]
  },
  {
   "title": "RSS responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (result) (bot_rss_responses_total - bot_rss_responses_total offset 5m)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ERROR ANALYTICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (type) (increase(bot_errors_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (bot_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}