name: 🛠️ Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Target architecture (amd64 or arm64)'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker buildx build \
          --platform linux/${{ github.event.inputs.architecture }} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/cs2-update-docker:${{ github.event.inputs.architecture }} \
          --output type=docker \
          .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/cs2-update-docker:latest
